# Form implementation generated from reading ui file 'myquizwindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_quizwindow(object):
    def setupUi(self, quizwindow):
        quizwindow.setObjectName("quizwindow")
        quizwindow.resize(620, 120)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(quizwindow.sizePolicy().hasHeightForWidth())
        quizwindow.setSizePolicy(sizePolicy)
        quizwindow.setMinimumSize(QtCore.QSize(620, 120))
        quizwindow.setMaximumSize(QtCore.QSize(620, 120))
        self.lcdNumber = QtWidgets.QLCDNumber(quizwindow)
        self.lcdNumber.setGeometry(QtCore.QRect(550, 10, 60, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber.sizePolicy().hasHeightForWidth())
        self.lcdNumber.setSizePolicy(sizePolicy)
        self.lcdNumber.setMinimumSize(QtCore.QSize(60, 50))
        self.lcdNumber.setMaximumSize(QtCore.QSize(60, 50))
        self.lcdNumber.setObjectName("lcdNumber")
        self.submit_button = QtWidgets.QPushButton(quizwindow)
        self.submit_button.setGeometry(QtCore.QRect(406, 70, 122, 50))
        self.submit_button.setMinimumSize(QtCore.QSize(122, 50))
        self.submit_button.setMaximumSize(QtCore.QSize(122, 50))
        self.submit_button.setObjectName("submit_button")
        self.widget = QtWidgets.QWidget(quizwindow)
        self.widget.setGeometry(QtCore.QRect(10, 10, 513, 56))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_wordtranslation = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_wordtranslation.setFont(font)
        self.label_wordtranslation.setText("")
        self.label_wordtranslation.setObjectName("label_wordtranslation")
        self.verticalLayout.addWidget(self.label_wordtranslation)
        self.test_lineEdit = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.test_lineEdit.sizePolicy().hasHeightForWidth())
        self.test_lineEdit.setSizePolicy(sizePolicy)
        self.test_lineEdit.setMinimumSize(QtCore.QSize(511, 30))
        self.test_lineEdit.setMaximumSize(QtCore.QSize(511, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.test_lineEdit.setFont(font)
        self.test_lineEdit.setText("")
        self.test_lineEdit.setObjectName("test_lineEdit")
        self.verticalLayout.addWidget(self.test_lineEdit)

        self.retranslateUi(quizwindow)
        QtCore.QMetaObject.connectSlotsByName(quizwindow)

    def retranslateUi(self, quizwindow):
        _translate = QtCore.QCoreApplication.translate
        quizwindow.setWindowTitle(_translate("quizwindow", "Word Quiz"))
        self.submit_button.setText(_translate("quizwindow", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    quizwindow = QtWidgets.QWidget()
    ui = Ui_quizwindow()
    ui.setupUi(quizwindow)
    quizwindow.show()
    sys.exit(app.exec())
